### ISSUE TITLE
send workshop survey links to mailing lists

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/Workshops#1]
In order to augment the visibility of the workshop, we discussed having @sammyjava first make any desired updates to the survey (he has already done the "who are you, please?", and if we don't hear of any other additions from the group we'll just call that good). Then @cdtown will send to his arabidopsis lists and we'll have @jd-campbell post links to home pages. Other venues?

**Comment by cdtown** [comment]
Yes.
I will write a brief spiel and post to arab-net and medicago-net (not exactly those names).
One of us (could be me) should ask David Grant to post to the soybean group.

**Comment by adf-ncgr** [comment]
Thanks @cdtown - if you accept your invitation to join the github legumefederation organization 
(just re-invited you), I will officially assign this issue to you!

**Comment by sammyjava** [comment]
YES: single-purpose email to the legume newsletter list, rather than buried in the newsletter, which they may just delete because it's a newsletter. (I had envisioned this being a standalone survey, not part of a newsletter.)

**Comment by cdtown** [comment]
How do I “accept”?

**Comment by adf-ncgr** [comment]
I think you should be receiving an email with a link to click- let me know if not...

**Comment by jd-campbell** [comment]
The stand alone survey link is scheduled to posted on multiple Twitter and Facebook pages for the next two weeks.

=========================
Jacqueline D. Campbell (Farrell), PhD
Iowa State University
jdjax@iastate.edu
##Sent from my iPhone
##Please excuse any spelling or grammar errors.
________________________________

**Comment by adf-ncgr** [comment]
@cdtown the issue is now assigned to you; feel free to post your draft verbiage in this comment thread, but give me a few minutes to ensure that the other subteam members are watchers of the repository and will be notified of updates automagically...

**Comment by vivekkrish** [comment]
@adf-ncgr, might be a good idea to explicitly define and organize members of each of sub-team as GitHub teams (https://github.com/orgs/LegumeFederation/teams). This will enable easy management of the relationships between sub-teams and their related repositories/permissions/notifications etc. Thanks!

**Comment by adf-ncgr** [comment]
@vivekkrish thanks for the suggestion, will give it a try although it's unclear to me whether I will
thereby be able to force them to watch the repository?

**Comment by vivekkrish** [comment]
@adf-ncgr, I believe when a user is given push access to a repo (i.e. permission level "Write" or "Admin"), the repo is automatically added to the users' **Watch** list.

**Comment by adf-ncgr** [comment]
@vivekkrish I think you are right. now that @LegumeFederation/workshops is a team, I think they are all subscribed. @cdtown you have greenlight to do your drafting now...

**Comment by cdtown** [comment]
Draft letter to be sent out with the survey link:

Subject Line: Workshop on Legume Bioinformatics

Content: The Legume Federation is organizing and hosting a workshop on Legume Bioinformatics to be held in Santa Fe, New Mexico in March 2018.  The purpose of the workshop is to familiarize the attendees with the suite of tools and resources that is being developed by the LegFed group as well as to provide relevant background information on other tools and resources and solicit community feedback on needs for future development efforts.
Interested individuals are requested to complete the questionnaire at the link below in order to facilitate workshop planning.
The Legume Federation is an alliance of research groups that provide informatics resources to the research and breeding communities for a range of legume species, and aims to further enrich these resources by integrating data sets and developing links between species at the genomic, genetic and phenotypic levels. The project is supported by the National Science Foundation.

**Comment by adf-ncgr** [comment]
OK, I made a few tweaks but looks good to me (assuming you'll put the link in the actual text when sending); @LegumeFederation/workshops please indicate your satisfaction or make further changes and alert when you think it's ready for shipping.

**Comment by cdtown** [comment]
I would like to send this out today (should have done it last week).
But I can't find the link to the final survey.
Somebody please provide.
Thanks!

**Comment by cdtown** [comment]
Sent to arab-gen@net.bio.net; medicago@net.bio.net and to David Grant with a request to post to the soybean list-serve.
