### ISSUE TITLE
identify guest speakers

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/Workshops#7]
likely will be from other federation partners or projects developing the tools upon which we rely

**Comment by adf-ncgr** [comment]
@cdtown I believe you are doing this now, so assigning to you to make it official, and I believe we are targeting Mar 21-23 unless key participants will be unavailable then; let me know if you think I got that wrong.

**Comment by cdtown** [comment]
Following messages sent:
Dear XXX
The Legume Federation is organizing an instructional workshop at NCGR in Santa Fe, with tentative dates of March 21-23, 2018
The purpose of the workshop is to expose legume biologists with the suite of tools that are being developed with the LegFed project and at the same time collect suggestions and ideas for future directions, including strengthening ties with other groups involved in legume bioinformatics.

XXX=Nevin: On behalf of the organizing group, I would like to invite you to join us in the workshop with the idea that you would present the HapMap work and perhaps join in other aspects of the instructional process as appropriate.
XXX=David: On behalf of the organizing group, I would like to invite you to join us in the workshop with the idea that you would present Soybase and any other genetic, genomic and trait resources that you manage, particularly as they relate to the breeding community. And perhaps join in other aspects of the instructional process as appropriate.
XXX=Patrick: On behalf of the organizing group, I would like to invite you to join us in the workshop with the idea that you would present the Alfalfa Breeders Tool Box as well as other legume-oriented resources at the Noble Foundation. And perhaps join in other aspects of the instructional process as appropriate.

Common text:
I hope very much that you will be able to accept our invitation (we will cover all your expenses). In the event that you are willing to join us, but those dates are not possible, please let us know some alternatives. We would like to choose dates that are convenient for all our invited speakers.

We look forward to hearing from you.

Best

Chris

**Comment by adf-ncgr** [comment]
per discussion, let's see if we can get someone from phytozome to join us; @cdtown will do the honors, if I'm not mistaken

**Comment by cdtown** [comment]
Nevin has accepted. March 21-23 works but not available 3/9 to 3/18. 

David Grant has accepted. He has another commitment 3/22-25, which he could change but would prefer not to. All other dates OK for him.

Patrick Zhao has accepted. He's out of the country 2/27 to 3/19. Hi kids are on Spring Break 3/19-23. He might bring them with him. He'd prefer 3/22-24 allowing him to drive out on 3/21 rather than 3/20.

David Goodstein accepted with no comment of dates/availability.

**Comment by cdtown** [comment]
Hi Chris, 

Good to know that you are organizing the highly needed workshop. We met at a Nobel foundation workshop as invited speakers several years ago.  We are working on developing a variety of new strategies to integrate diverse big-data from the public and in-house database for soybean trait gene/causative allele discovery and their underlying gene network reconstruction. Now we mainly focus on integration of structural genomic and transcriptome sequencing data, genetic QTL and phenotypic data, and small RNA and methylation data.  We are also working on comparing transcriptomes of soybean and peanut seeds. We focus on data mining strategies instead of tool and database development and management. The workshop are extremely useful for us, and our participation may be beneficial to you as well. 

However, my travel budget is very limited in the coming year.  Do you have sufficient fund to support me or additional staff in my lab? If you are beneficial to you, I can give a short oral presentation as one of your downstream user. 

Best regards, 

Charles 


Yong-qiang Charles An, Ph.D.  
Research Molecular Biologist/Lead Scientist
Plant Genetics Research, MWA, ARS, USDA
Donald Danforth Plant Science Center
975 North Warson Road
St. Louis, Missouri  63132, USA
Web:  http://www.ars.usda.gov/pandp/people/people.htm?personid=43793
Email: yong-qiang.an@ars.usda.gov; yan@danforthcenter.org
Tel: 314-587-1669; Fax: 314-587-1769

**Comment by adf-ncgr** [comment]
all invited speakers confirmed their availability. Following up now with other fed members, but going to close this as it has served the purpose of getting us to finalize the dates.
